project:
  type: website
  execute-dir: project
  output-dir: docs

execute:
  freeze: auto

website:
  title: "NCEAS Sci Comp Workshop - Tidyverse"
  favicon: images/scicomptools_hex.png
  repo-url: https://github.com/NCEAS/scicomp-workshop-tidyverse
  repo-actions: [issue]
  twitter-card: true
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - wrangle.qmd
      - summarize.qmd
      - reshape.qmd
      - join.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/NCEAS/scicomp-workshop-tidyverse
  page-footer:
    center: "Copyright 2022, NCEAS"
    background: secondary

format:
  html:
    theme:
       light: yeti
       dark: cyborg
    css: styles.css
    toc: true
    link-external-newwindow: true
    link-external-icon: false
    