on:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          version: 0.9.600
      
      # add software dependencies here
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # The R version to download (if necessary) and use.
          
      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
          
      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          install.packages("palmerpenguins")
          install.packages("here")
          install.packages("knitr")
          install.packages("dplyr")
          install.packages("tidyr")
          install.packages("quarto")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .          
          
      # To publish to Netlify, RStudio Connect, or GitHub Pages, uncomment
      # the appropriate block below
      
      # - name: Publish to Netlify (and render)
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: netlify
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        
      # - name: Publish to RStudio Connect (and render)
      #   uses: quarto-dev/quarto-actions/publish@v2
      #   with:
      #     target: connect
      #     CONNECT_SERVER: enter-the-server-url-here
      #     CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }} 

      - name: Publish to GitHub Pages (and render)
         uses: quarto-dev/quarto-actions/publish@v2
         with:
           target: gh-pages
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
      
